### ISSUE TITLE
Question: Is there an AngularJS version of this d3 example code?

### ISSUE THREAD

**Issue by Shawful** [alignedleft/scattered-scatterplot#2]
I'm using <a href="yeoman.io">yeoman</a> and I'm finding difficulty finding AngularJS examples of d3 graphs and charts.  From what I've read <a href="https://docs.angularjs.org/guide/directive">directives</a> must be made for each graph.  Any idea of some articles that could help?  Or is it possible to translate the graphs used in your videos into angularJS code?  I will be at OSCON 2015 in Portland and working with AngularJS, so I would really appreciate a version that implements the examples in AngularJS.  The only <a href="https://github.com/WealthBar/angular-d3">github examples</a> I've found have been using coffee script, which might as well have been written in Klingon.  I'm not saying Klingon is difficult - I'm just saying that I haven't taken the time to learn.

Cheers

**Comment by Shawful** [comment]
@revanthreddy

**Comment by scotthmurray** [comment]
Well, this course/workshop isn't about Angular, so these examples won't incorporate it. I'd suggest searching the D3 Google Group.  Lots of people have already explored (and asked about) using Angular with D3.

**Comment by Shawful** [comment]
I realized that after viewing the content a bit more.  And I was able to get other example to work as-is in an angular environment to serve the code using yeoman.  I think it was all good prep for the course at any rate.
